### ISSUE TITLE
Add number of contributors to stats

### ISSUE THREAD

**Issue by sarahscott** [CocoaPods/metrics.cocoapods.org#30]
It would be helpful to see how many people contribute to a Pod on GitHub!

![](http://media2.giphy.com/media/a5l0qyXYQMSd2/giphy.gif)

**Comment by kylef** [comment]
@sarahscott Isn't this already exposed?

![screen shot 2015-06-17 at 15 10 27](https://cloud.githubusercontent.com/assets/44164/8219979/114ebc4e-1503-11e5-8120-06107aab2f93.png)

**Comment by segiddins** [comment]
We already have these :)
http://metrics.cocoapods.org/api/v1/pods/RestKit

**Comment by sarahscott** [comment]
:+1:
