### ISSUE TITLE
Wrong stars number

### ISSUE THREAD

**Issue by skywinder** [CocoaPods/metrics.cocoapods.org#31]
Hi. Here is mu profile page:
https://cocoapods.org/owners/3223

And there is 0 stars for [GaugeKit](https://github.com/skywinder/GaugeKit)
![screen shot 2015-07-17 at 16 26 13](https://cloud.githubusercontent.com/assets/3356474/8748090/bf101d8c-2ca0-11e5-82cb-9c11e537525d.png)

But there is more 450 stars already.

**Comment by neonichu** [comment]
I believe the star count is collected only once when a new version of the Pod is submitted. Could that be the cause of this behaviour by any chance?

**Comment by orta** [comment]
Nah, not in this case, there's a daily runner that grabs them. @hanke - any ideas?

**Comment by k0nserv** [comment]
Odd, it should be a prime candidate for the runner to select it

**Comment by k0nserv** [comment]
@skywinder 

GaugeKit now has correct stats :tada: 
![image](https://cloud.githubusercontent.com/assets/1333960/8819865/753c7f4e-3050-11e5-8223-8a8792037b69.png)

Thanks for reporting this issue.

**Comment by skywinder** [comment]
Hooray! Thanks! :+1:
