### ISSUE TITLE
GitHub section not updating

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/metrics.cocoapods.org#34]
i've noticed that the stats under the GitHub section are not updating. for example, the latest version i pushed for this pod https://cocoapods.org/pods/Gloss today shows:

![screen shot 2015-08-22 at 1 47 06 pm](https://cloud.githubusercontent.com/assets/5456481/9425169/4e1154e8-48d4-11e5-990a-e8f8fbb76aab.png)

despite their being values `148`, `6`, `6`, `1`, `3`, `0` for the stats respectively

**Comment by orta** [comment]
I expect  #36 will fix this when deployed after a day or two for it to get through all pods

**Comment by hkellaway** [comment]
Still not seeing an update despite waiting a few days and updating the pod since :confounded:

**Comment by orta** [comment]
It's not deployed, I'll do so now.

**Comment by hkellaway** [comment]
stats update :tada:

**Comment by segiddins** [comment]
:+1:

**Comment by orta** [comment]
Thanks for the push!
