### ISSUE TITLE
Pod stats via the Metrics API have not been updating since October 21st

### ISSUE THREAD

**Issue by salqadri** [CocoaPods/metrics.cocoapods.org#43]
Hey,

We have been using the metrics API to monitor traction of our SDKs (http://metrics.cocoapods.org/api/v1/pods/Firebase.json). But lately, since October 21st to be precise, the API has stopped updating the stats for any pod. I checked the operational status and metrics is green, yet for some reason the updated_at field has been stuck at October 21st. What is going on?

**Comment by segiddins** [comment]
Did you try having cocoadocs redocument the pod?

**Comment by segiddins** [comment]
(The GitHub stats say they were updated today)

**Comment by salqadri** [comment]
Don't care for github stats. I can use Github apis for that. I specifically want install stats, particularly "app_total" but also things like "pod_try_total".

**Comment by segiddins** [comment]
I just added some logging to stats.cocoapods.org, so I'll check up on the daily task to sync those numbers in the morning

**Comment by salqadri** [comment]
All the metrics are still stuck at 2016-10-21:
http://metrics.cocoapods.org/api/v1/pods/Firebase.json
http://metrics.cocoapods.org/api/v1/pods/Facebook-iOS-SDK.json
http://metrics.cocoapods.org/api/v1/pods/Google.json

**Comment by orta** [comment]
Yep, it's the same for _every_  pod, I'm afraid we're still figuring out what are options are about bringing them all back up to date

**Comment by patchthecode** [comment]
Thanks. I am experiencing the same issue here.
All my metrics are stuck. hoping for a solution to this.

**Comment by patchthecode** [comment]
I see the issue is closed.
Has it been fixed?
http://metrics.cocoapods.org/api/v1/pods/JTAppleCalendar.json

**Comment by girtis** [comment]
Looking forward to a resolution of this one, we rely on these metrics for tracking as well.

**Comment by orta** [comment]
This is still being worked on, it's not an overnight thing I'm afraid

**Comment by patchthecode** [comment]
I wish we can at least get an idea of the problem? (even thought we may not be super technical to understand it all)

**Comment by segiddins** [comment]
Segment discontinued the product we were using to keep track of all of these events, so we're migrating to a new backend with their help

**Comment by patchthecode** [comment]
@segiddins Thanks very much for the information. I had one last question. When all this is resolved, will the real downloads count be up-to-date? Or, will it just continue the download metrics from where it paused months ago :/

**Comment by segiddins** [comment]
I dont know

**Comment by patchthecode** [comment]
Alright then. hoping for the best.

**Comment by endocrimes** [comment]
@patchthecode @salqadri I just updated the stats service to point to the new Redshift deployment, so the data should now be up to date.

AFAICT there is no actually missing data from the transition period, however, I could be wrong.

**Comment by patchthecode** [comment]
@DanToml seems downloads are still at 22,415 for this pod.
https://cocoapods.org/pods/JTAppleCalendar

Well, if its fixed, then I do not mind the out-of-date download count.
Thanks for all your work.

**Comment by orta** [comment]
Stats updates run nightly, so it'll need a 24hrs to be sure

**Comment by endocrimes** [comment]
@patchthecode The stats are cached daily, so this should be updated on the next run - It'd be great if you could let me know when you see the change.

**Comment by patchthecode** [comment]
@DanToml thanks i will.

**Comment by girtis** [comment]
Thanks for fixing this! Definitely something to be Thankful for! 🦃

**Comment by patchthecode** [comment]
@DanToml my downloads have been correctly updated. Thanks for your good work.

**Comment by salqadri** [comment]
Thanks @DanToml works like a charm!
