### ISSUE TITLE
[Question] Is the only way to update the by releasing a new pod version?

### ISSUE THREAD

**Issue by patchthecode** [CocoaPods/metrics.cocoapods.org#44]
Ok. I have updated some of my documentation etc and added some tests on my cocoapod. 

In order for me to get a higher metric score on cocoapods, do I need to release a new version of my pod so that your site can pick up that I have actually added more documentation and tests?

Or is there some way I can update the metric without releasing a whole new version.?

Thanks for your work guys.

**Comment by orta** [comment]
New releases only, yes 👍 

CocoaPods does not check your master branch for this kind of metadata, it's too much work for 25k pods

**Comment by patchthecode** [comment]
I understand its too much work for CocoaPods itself to initiate the check. But would it be a bad idea if it is the other way around?

A user can signal to Cocoapods to check (instead of cocoapods initiating the check). This will be similar to what is already happening, except that instead of a pushToTrunk doing the trigger, a signal of some sort from the user is triggering cocoapods to check. 

If its a bad idea or wont work, then its all good. No worries. I just thought that updating a pod version just to update some documentation could have been done another way. Either way, thanks guys. 👍

**Comment by orta** [comment]
Nah, it's not a good idea - it doesn't represent what the user will get when they use the pod through trunk

**Comment by patchthecode** [comment]
True. Makes sense. I missed that point. Scratch that idea then. :]
