### ISSUE TITLE
My pod's CocoaPod metrics are wrong.

### ISSUE THREAD

**Issue by WilliamZang** [CocoaPods/metrics.cocoapods.org#48]
- [x] I've read and understood the *CONTRIBUTING guidelines and have done my best effort to follow.

# Report
## What did you do?
Invoked https://metrics.cocoapods.org/api/v1/pods/EasyReact.json

# What did you expected to happen?
Expected to see updated stats for today, star count of Github should be 1200+ but only 6.

# What happened instead?
Star count of Github is 6.

# CocoaPods Environment
N/A

# Project that demonstrates the issue
https://metrics.cocoapods.org/api/v1/pods/EasyReact.json

**Comment by codeface-io** [comment]
Yep, the github stats of my pod have not updated since around April.

But this is a duplicate issue no? https://github.com/CocoaPods/metrics.cocoapods.org/issues/45

**Comment by amorde** [comment]
Closing in favor of #45
