### ISSUE TITLE
Does this Api still work ? 

### ISSUE THREAD

**Issue by jingleiaf** [CocoaPods/metrics.cocoapods.org#50]
It seems that there is a server issue : 
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/123410196/221546904-5f25a490-7029-4846-9921-a0cd15f0a03a.png">

**Comment by orta** [comment]
Thanks, same issue as https://github.com/CocoaPods/CocoaPods/issues/11789#issuecomment-1445689589 - think I've fixed it in all now
